#!/bin/bash

mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

backline() {
  printf "\e[1A"
  echo -ne "\\r\033[2K"
}

trap 'rm -f "/tmp/exec.$$"' 0
trap 'exit $?' 1 2 3 15

printf "\n${mag}[ENTER]${end}${cyn} OS (mac|linux):${end} "
read -r HAFIZ_ENROLL_OS

backline
printf "${mag}[ENTER]${end}${cyn} One-Time ID:${end} "
read -r HAFIZ_ENROLL_FOR

if [ -z "$HAFIZ_ENROLL_FOR" ]; then
  backline
  printf "${mag}[ENTER]${end}${cyn} Master Password:${end} "
  read -rs HAFIZ_ENROLL_PASSWORD
  backline
  echo -e "\nThis may take a minute..."
  curl -sSL "https://ayazhafiz.com/bin/enroll?os=$HAFIZ_ENROLL_OS&password=$HAFIZ_ENROLL_PASSWORD" | cat >/tmp/exec.$$
else
  backline; backline
  echo -e "\nThis may take a minute..."
  curl -sSL "https://ayazhafiz.com/bin/enroll?os=$HAFIZ_ENROLL_OS&for=$HAFIZ_ENROLL_FOR" | cat >/tmp/exec.$$
fi

backline; backline
chmod +x /tmp/exec.$$
sudo /tmp/exec.$$
