#!/bin/bash
# bash -c "$(curl //enroll)"

BIN="/usr/local/bin"
SELENIUM_VERSION=3.9
CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip"
CHROMEDRIVER_PATH="$HOME/Downloads/chromedriver"
SCRIPT_URL="https://gist.githubusercontent.com/ayazhafiz/aefae50d7b9a302cbb3a627f6157905a/raw/7d61017156a4cce9a4f673fe9598dc8138433598/enroll"
SOURCE_FILE="$HOME/.bashrc"

# Make sure bin exists
if [ ! -d "$BIN" ]; then
  sudo mkdir $BIN
fi

### Dependencies
# Pip
echo "Checking for pip..."
if ! hash pip; then
  sudo easy_install pip
  printf "\tpip downloaded\n"
else
  printf "\tpip already installed\n"
fi

# Selenium
echo "Installing selenium..."
sudo pip install selenium==$SELENIUM_VERSION

# Chromedriver
echo "Installing chromedriver..."
sudo curl "$CHROMEDRIVER_URL" -o "$CHROMEDRIVER_PATH.zip"
unzip "$CHROMEDRIVER_PATH.zip" -d "$CHROMEDRIVER_PATH"
sudo mv "$CHROMEDRIVER_PATH/chromedriver" "$BIN/chromedriver"
yes | rm "$CHROMEDRIVER_PATH.zip"
rm -rf "$CHROMEDRIVER_PATH"

# Enroll script
echo "Installing enroll script..."
sudo curl "$SCRIPT_URL" -o "$BIN/enroll"
sudo chmod +x "$BIN/enroll"

# Get ENV variables for login
echo ""
echo "Type your VUnet ID, followed by [ENTER]: "
read -r ID

echo "Type your VUnet password, followed by [ENTER]: "
read -r PW

echo "export VUNET_ID=$ID" > "$SOURCE_FILE"
echo "export VUNET_PW=$PW" >> "$SOURCE_FILE"

echo "VUnet ID, VUnet password saved as environment variables to $SOURCE_FILE."

printf "\nAdd the following to your terminal startup script:"
printf "\n\tsource %s && clear\n" "$SOURCE_FILE"
echo "Restart your terminal, and the command will be avaliable with 'enroll'."
